= Teragrep Authentication Module for Apache Kafka

== Features

Easy and simple to use Teragrep Authenticator for Kafka.

== Configuration

[text]
----
listeners=EXTERNAL://:9092
----

`server.callback.handler.class` sets it for broker clients

`client.callback.handler.class` it for non-broker clients

[text]
----
listener.name.external.plain.sasl.server.callback.handler.class=com.teragrep.kaf_05.TeragrepAuthenticateCallbackHandler
listener.name.external.plain.sasl.client.callback.handler.class=com.teragrep.kaf_05.TeragrepAuthenticateCallbackHandler
----

== Documentation

See the official documentation on https://docs.teragrep.com[docs.teragrep.com].

== How to use

[text]
----
CLASSPATH="/opt/teragrep/kaf_05/share/kaf_05.jar"
----

== Contributing

You can involve yourself with our project by https://github.com/teragrep/kaf_05/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories.
